### ISSUE TITLE
Coordinating lammps potential name

### ISSUE THREAD

**Issue by pmrv** [pyiron-workshop/potentials-workshop-2021#29]
We should make sure that all three fitting classes have the same way of getting the final lammps potential.  I added a `lammps_potential` property to the RuNNer class, I took the name from @yury-lysogorskiy.  @Leimeroth do you have a method like this already in AtomicRex?

Any other suggestions for the name or method vs. property?

**Comment by Leimeroth** [comment]
Yes I have the potential_as_pd_df() method, which it returns it in the necessary format for lammps.

It does not work when the job is reloaded because it uses the input.atom_types which are not recovered correctly from hdf, but it can easily be fixed manually. Alternatively I suggest using a property with hardcoded "Cu" as species for the workshop

**Comment by pmrv** [comment]
I think hardcoding the species would be acceptable for now.

**Comment by Leimeroth** [comment]
Added a property with hardcoded Cu. Can we close this?
